export default {
  AFN: { country: "Afghanistan", currency_code: "AFN", flag: "af" },
  ALL: { country: "Albania", currency_code: "ALL", flag: "al" },
  DZD: { country: "Algeria", currency_code: "DZD", flag: "dz" },
  USD: { country: "Virgin Islands, U.S.", currency_code: "USD", flag: "vi" },
  EUR: { country: "Spain", currency_code: "EUR", flag: "es" },
  AOA: { country: "Angola", currency_code: "AOA", flag: "ao" },
  XCD: {
    country: "Saint Vincent and the Grenadines",
    currency_code: "XCD",
    flag: "vc"
  },
  ARS: { country: "Argentina", currency_code: "ARS", flag: "ar" },
  AMD: { country: "Armenia", currency_code: "AMD", flag: "am" },
  AWG: { country: "Aruba", currency_code: "AWG", flag: "aw" },
  AUD: { country: "Tuvalu", currency_code: "AUD", flag: "tv" },
  AZN: { country: "Azerbaijan", currency_code: "AZN", flag: "az" },
  BSD: { country: "Bahamas", currency_code: "BSD", flag: "bs" },
  BHD: { country: "Bahrain", currency_code: "BHD", flag: "bh" },
  BDT: { country: "Bangladesh", currency_code: "BDT", flag: "bd" },
  BBD: { country: "Barbados", currency_code: "BBD", flag: "bb" },
  BYR: { country: "Belarus", currency_code: "BYR", flag: "by" },
  BZD: { country: "Belize", currency_code: "BZD", flag: "bz" },
  XOF: { country: "Togo", currency_code: "XOF", flag: "tg" },
  BMD: { country: "Bermuda", currency_code: "BMD", flag: "bm" },
  BTN: { country: "Bhutan", currency_code: "BTN", flag: "bt" },
  BOB: { country: "Bolivia", currency_code: "BOB", flag: "bo" },
  BAM: { country: "Bosnia and Herzegovina", currency_code: "BAM", flag: "ba" },
  BWP: { country: "Botswana", currency_code: "BWP", flag: "bw" },
  NOK: { country: "Svalbard and Jan Mayen", currency_code: "NOK", flag: "sj" },
  BRL: { country: "Brazil", currency_code: "BRL", flag: "br" },
  BND: { country: "Brunei", currency_code: "BND", flag: "bn" },
  BGN: { country: "Bulgaria", currency_code: "BGN", flag: "bg" },
  BIF: { country: "Burundi", currency_code: "BIF", flag: "bi" },
  KHR: { country: "Cambodia", currency_code: "KHR", flag: "kh" },
  XAF: { country: "Gabon", currency_code: "XAF", flag: "ga" },
  CAD: { country: "Canada", currency_code: "CAD", flag: "ca" },
  CVE: { country: "Cape Verde", currency_code: "CVE", flag: "cv" },
  KYD: { country: "Cayman Islands", currency_code: "KYD", flag: "ky" },
  CLP: { country: "Chile", currency_code: "CLP", flag: "cl" },
  CNY: { country: "China", currency_code: "CNY", flag: "cn" },
  COP: { country: "Colombia", currency_code: "COP", flag: "co" },
  KMF: { country: "Comoros", currency_code: "KMF", flag: "km" },
  NZD: { country: "Tokelau", currency_code: "NZD", flag: "tk" },
  CRC: { country: "Costa Rica", currency_code: "CRC", flag: "cr" },
  HRK: { country: "Croatia", currency_code: "HRK", flag: "hr" },
  CUP: { country: "Cuba", currency_code: "CUP", flag: "cu" },
  CZK: { country: "Czech Republic", currency_code: "CZK", flag: "cz" },
  DKK: { country: "Greenland", currency_code: "DKK", flag: "gl" },
  DJF: { country: "Djibouti", currency_code: "DJF", flag: "dj" },
  DOP: { country: "Dominican Republic", currency_code: "DOP", flag: "do" },
  ECS: { country: "Ecuador", currency_code: "ECS", flag: "ec" },
  EGP: { country: "Egypt", currency_code: "EGP", flag: "eg" },
  SVC: { country: "El Salvador", currency_code: "SVC", flag: "sv" },
  GBP: { country: "Wales", currency_code: "GBP", flag: "" },
  ERN: { country: "Eritrea", currency_code: "ERN", flag: "er" },
  ETB: { country: "Ethiopia", currency_code: "ETB", flag: "et" },
  FKP: { country: "Falkland Islands", currency_code: "FKP", flag: "fk" },
  FJD: { country: "Fiji Islands", currency_code: "FJD", flag: "fj" },
  XPF: { country: "Wallis and Futuna", currency_code: "XPF", flag: "wf" },
  GMD: { country: "Gambia", currency_code: "GMD", flag: "gm" },
  GEL: { country: "Georgia", currency_code: "GEL", flag: "ge" },
  GHS: { country: "Ghana", currency_code: "GHS", flag: "gh" },
  GIP: { country: "Gibraltar", currency_code: "GIP", flag: "gi" },
  QTQ: { country: "Guatemala", currency_code: "QTQ", flag: "gt" },
  GNF: { country: "Guinea", currency_code: "GNF", flag: "gn" },
  CFA: { country: "Guinea-Bissau", currency_code: "CFA", flag: "gw" },
  GYD: { country: "Guyana", currency_code: "GYD", flag: "gy" },
  HTG: { country: "Haiti", currency_code: "HTG", flag: "ht" },
  HNL: { country: "Honduras", currency_code: "HNL", flag: "hn" },
  HKD: { country: "Hong Kong", currency_code: "HKD", flag: "hk" },
  HUF: { country: "Hungary", currency_code: "HUF", flag: "hu" },
  ISK: { country: "Iceland", currency_code: "ISK", flag: "is" },
  INR: { country: "India", currency_code: "INR", flag: "in" },
  IDR: { country: "Indonesia", currency_code: "IDR", flag: "id" },
  IRR: { country: "Iran", currency_code: "IRR", flag: "ir" },
  IQD: { country: "Iraq", currency_code: "IQD", flag: "iq" },
  ILS: { country: "Israel", currency_code: "ILS", flag: "il" },
  JMD: { country: "Jamaica", currency_code: "JMD", flag: "jm" },
  JPY: { country: "Japan", currency_code: "JPY", flag: "jp" },
  JOD: { country: "Jordan", currency_code: "JOD", flag: "jo" },
  KZT: { country: "Kazakhstan", currency_code: "KZT", flag: "kz" },
  KES: { country: "Kenya", currency_code: "KES", flag: "ke" },
  KWD: { country: "Kuwait", currency_code: "KWD", flag: "kw" },
  KGS: { country: "Kyrgyzstan", currency_code: "KGS", flag: "kg" },
  LAK: { country: "Laos", currency_code: "LAK", flag: "la" },
  LVL: { country: "Latvia", currency_code: "LVL", flag: "lv" },
  LBP: { country: "Lebanon", currency_code: "LBP", flag: "lb" },
  LSL: { country: "Lesotho", currency_code: "LSL", flag: "ls" },
  LRD: { country: "Liberia", currency_code: "LRD", flag: "lr" },
  LYD: { country: "Libyan Arab Jamahiriya", currency_code: "LYD", flag: "ly" },
  CHF: { country: "Switzerland", currency_code: "CHF", flag: "ch" },
  LTL: { country: "Lithuania", currency_code: "LTL", flag: "lt" },
  MOP: { country: "Macao", currency_code: "MOP", flag: "mo" },
  MKD: { country: "North Macedonia", currency_code: "MKD", flag: "mk" },
  MGF: { country: "Madagascar", currency_code: "MGF", flag: "mg" },
  MWK: { country: "Malawi", currency_code: "MWK", flag: "mw" },
  MYR: { country: "Malaysia", currency_code: "MYR", flag: "my" },
  MVR: { country: "Maldives", currency_code: "MVR", flag: "mv" },
  MRO: { country: "Mauritania", currency_code: "MRO", flag: "mr" },
  MUR: { country: "Mauritius", currency_code: "MUR", flag: "mu" },
  MXN: { country: "Mexico", currency_code: "MXN", flag: "mx" },
  MDL: { country: "Moldova", currency_code: "MDL", flag: "md" },
  MNT: { country: "Mongolia", currency_code: "MNT", flag: "mn" },
  MAD: { country: "Western Sahara", currency_code: "MAD", flag: "eh" },
  MZN: { country: "Mozambique", currency_code: "MZN", flag: "mz" },
  MMR: { country: "Myanmar", currency_code: "MMR", flag: "mm" },
  NAD: { country: "Namibia", currency_code: "NAD", flag: "na" },
  NPR: { country: "Nepal", currency_code: "NPR", flag: "np" },
  ANG: { country: "Netherlands Antilles", currency_code: "ANG", flag: "an" },
  NIO: { country: "Nicaragua", currency_code: "NIO", flag: "ni" },
  NGN: { country: "Nigeria", currency_code: "NGN", flag: "ng" },
  KPW: { country: "North Korea", currency_code: "KPW", flag: "kp" },
  OMR: { country: "Oman", currency_code: "OMR", flag: "om" },
  PKR: { country: "Pakistan", currency_code: "PKR", flag: "pk" },
  PAB: { country: "Panama", currency_code: "PAB", flag: "pa" },
  PGK: { country: "Papua New Guinea", currency_code: "PGK", flag: "pg" },
  PYG: { country: "Paraguay", currency_code: "PYG", flag: "py" },
  PEN: { country: "Peru", currency_code: "PEN", flag: "pe" },
  PHP: { country: "Philippines", currency_code: "PHP", flag: "ph" },
  PLN: { country: "Poland", currency_code: "PLN", flag: "pl" },
  QAR: { country: "Qatar", currency_code: "QAR", flag: "qa" },
  RON: { country: "Romania", currency_code: "RON", flag: "ro" },
  RUB: { country: "Russian Federation", currency_code: "RUB", flag: "ru" },
  RWF: { country: "Rwanda", currency_code: "RWF", flag: "rw" },
  SHP: { country: "Saint Helena", currency_code: "SHP", flag: "sh" },
  WST: { country: "Samoa", currency_code: "WST", flag: "ws" },
  STD: { country: "Sao Tome and Principe", currency_code: "STD", flag: "st" },
  SAR: { country: "Saudi Arabia", currency_code: "SAR", flag: "sa" },
  SCR: { country: "Seychelles", currency_code: "SCR", flag: "sc" },
  SLL: { country: "Sierra Leone", currency_code: "SLL", flag: "sl" },
  SGD: { country: "Singapore", currency_code: "SGD", flag: "sg" },
  SBD: { country: "Solomon Islands", currency_code: "SBD", flag: "sb" },
  SOS: { country: "Somalia", currency_code: "SOS", flag: "so" },
  ZAR: { country: "South Africa", currency_code: "ZAR", flag: "za" },
  KRW: { country: "South Korea", currency_code: "KRW", flag: "kr" },
  SSP: { country: "South Sudan", currency_code: "SSP", flag: "ss" },
  LKR: { country: "SriLanka", currency_code: "LKR", flag: "" },
  SDG: { country: "Sudan", currency_code: "SDG", flag: "sd" },
  SRD: { country: "Suriname", currency_code: "SRD", flag: "sr" },
  SZL: { country: "Swaziland", currency_code: "SZL", flag: "sz" },
  SEK: { country: "Sweden", currency_code: "SEK", flag: "se" },
  SYP: { country: "Syria", currency_code: "SYP", flag: "sy" },
  TJS: { country: "Tajikistan", currency_code: "TJS", flag: "tj" },
  TZS: { country: "Tanzania", currency_code: "TZS", flag: "tz" },
  THB: { country: "Thailand", currency_code: "THB", flag: "th" },
  CDF: {
    country: "The Democratic Republic of Congo",
    currency_code: "CDF",
    flag: "cd"
  },
  TOP: { country: "Tonga", currency_code: "TOP", flag: "to" },
  TTD: { country: "Trinidad and Tobago", currency_code: "TTD", flag: "tt" },
  TND: { country: "Tunisia", currency_code: "TND", flag: "tn" },
  TRY: { country: "Turkey", currency_code: "TRY", flag: "tr" },
  TMT: { country: "Turkmenistan", currency_code: "TMT", flag: "tm" },
  UGX: { country: "Uganda", currency_code: "UGX", flag: "ug" },
  UAH: { country: "Ukraine", currency_code: "UAH", flag: "ua" },
  AED: { country: "United Arab Emirates", currency_code: "AED", flag: "ae" },
  UYU: { country: "Uruguay", currency_code: "UYU", flag: "uy" },
  UZS: { country: "Uzbekistan", currency_code: "UZS", flag: "uz" },
  VUV: { country: "Vanuatu", currency_code: "VUV", flag: "vu" },
  VEF: { country: "Venezuela", currency_code: "VEF", flag: "ve" },
  VND: { country: "Vietnam", currency_code: "VND", flag: "vn" },
  YER: { country: "Yemen", currency_code: "YER", flag: "ye" },
  ZMW: { country: "Zambia", currency_code: "ZMW", flag: "zm" },
  ZWD: { country: "Zimbabwe", currency_code: "ZWD", flag: "zw" }
};
